# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

blogs = Blog.create([{title: 'CRUD', body:'En informática, CRUD es el acrónimo de "Crear, Leer, Actualizar y Borrar" (del original en inglés: Create, Read, Update and Delete), que se usa para referirse a las funciones básicas en bases de datos o la capa de persistencia en un software. n computer programming, create, read, update, and delete[1] (as an acronym CRUD) are the four basic functions of persistent storage.[2] Alternate words are sometimes used when defining the four basic functions of CRUD, retrieve instead of read, modify instead of update, or destroy instead of delete. CRUD is also sometimes used to describe user interface conventions that facilitate viewing, searching, and changing information; often using computer-based forms and reports. The term was likely first popularized by James Martin in his 1983 book Managing the Data-base Environment.[1][3] The acronym may be extended to CRUDL to cover listing of large data sets which bring additional complexity such as pagination when the data sets are too large to hold easily in memory.'}, {title: 'Tom Clancy\'s The Division', body:'Tom Clancy\'s The Division is an online-only open world third-person shooter video game developed by Massive Entertainment and published by Ubisoft, with assistance from Red Storm Entertainment, for Microsoft Windows, PlayStation 4 and Xbox One. It was announced during Ubisoft\'s E3 2013 press conference, and was released worldwide on 8 March 2016. The Division is set in a near future New York City in the aftermath of a smallpox pandemic; the player, who is an agent of the eponymous Strategic Homeland Division, commonly referred to as simply "The Division", is tasked with helping the group rebuild its operations in Manhattan, investigate the nature of the outbreak, and combating criminal activity in its wake. The Division is structured with elements of role-playing games, as well as collaborative and player versus player online multiplayer. The game received positive reviews, and was a commercial success, with Ubisoft stating that the game broke the company\'s record for highest number of first-day sales. Furthermore, one week after the game\'s release, Ubisoft stated that The Division was the company\'s best-selling game, and the industry\'s biggest first-week launch for a new game franchise, which generated an estimated amount of $330 million globally.'}])
comments = Comment.create([{body:'is cool', blog: blogs[0] }]) 
